name: Run Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    # env:
      # add env here

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: Install requirements
      run: |        
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest --cov -v --tb=native
